### ISSUE TITLE
Device Approval

### ISSUE THREAD

**Issue by MuttiGiacomo** [MuttiGiacomo/tpa-homework1#1]
Device approval @DavidLeoni

**Comment by DavidLeoni** [comment]
mmm Abbiamo già un trailer:

https://github.com/oselin/diitpahomework1

**Comment by MuttiGiacomo** [comment]
Pensavo fosse sufficientemente diverso. Ho caricato una nuova proposta:
nel nuovo device le variabili sarebbero: angolo di lancio, dimensioni del corpo e angolo di lancio.
Il lavoro completo potrebbe essere composto dalla catapulta con qualcosa da lanciare e/o una macchina che la traina.
(In aggiunta alle variabili sto valutando di aggiungere la lunghezza del braccio).
Se secondo lei può andare, procedo a modificare il codice scritto per il trailer, altrimenti provvederò ad un'alternativa.
Rimango in attesa di una risposta.

**Comment by DavidLeoni** [comment]
La catapulta va bene, poi ci sarebbe da considerare i vincoli, in caso quali sarebbero? Ruote troppo grandi potrebbero toccare l'asta?

**Comment by MuttiGiacomo** [comment]
Va bene. Come vincoli metterei delle dimensioni massime per ogni pezzo e per l'angolo (oltre al fatto che siano dei valori positivi).
Li specificherò meglio nel README una volta definiti

**Comment by DavidLeoni** [comment]
più che min/max  vorrei vedere dei vincoli che mostrano ci sia interdipendenza tra i componenti, per avere qualcosa di non banale da testare - es  aggiungendo l'altezza del cassone potrebbe influire sui limiti dell'angolo

**Comment by MuttiGiacomo** [comment]
In aggiunta allora potrei mettre l'altezza della base dal suolo e imporre che non sia inferiore al raggio delle ruote o superiore al diametro. Se secondo lei i vincoli min/max e questi due di interdipendenza sono succifienti procedo con il codice.

**Comment by DavidLeoni** [comment]
ok
